services:

  # development container
  development:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    stdin_open: true

  # database
  postgresql:
    hostname: postgres_db
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=applesauce
      - POSTGRES_DB=example

  # web server
  webserver:
    hostname: webserver
    image: php:7.4-apache
    ports:
      - 9080:80
    volumes:
      - ../src:/var/www/html